import { STAKEHOLDER_FORBIDDEN_PATTERNS, checkBrandExposure } from '@qa/contracts';
import { LessonEntrySchema } from '@qa/contracts';

describe('@qa/contracts — brand-exposure', () => {
  it('STAKEHOLDER_FORBIDDEN_PATTERNS is a non-empty array of RegExp', () => {
    expect(Array.isArray(STAKEHOLDER_FORBIDDEN_PATTERNS)).toBe(true);
    expect(STAKEHOLDER_FORBIDDEN_PATTERNS.length).toBeGreaterThan(0);
    STAKEHOLDER_FORBIDDEN_PATTERNS.forEach((p) => expect(p).toBeInstanceOf(RegExp));
  });

  it('checkBrandExposure() returns null for clean text', () => {
    expect(checkBrandExposure('The QA team found 3 defects in the login flow.')).toBeNull();
  });

  it('checkBrandExposure() returns matching pattern when "aegis" appears', () => {
    expect(checkBrandExposure('Generated by Aegis framework v1.0')).toBeInstanceOf(RegExp);
  });

  it('checkBrandExposure() flags internal agent names', () => {
    expect(checkBrandExposure('Reviewed by qa-orchestrator')).toBeInstanceOf(RegExp);
    expect(checkBrandExposure('Written by qa-test-designer')).toBeInstanceOf(RegExp);
  });

  it('checkBrandExposure() flags events.jsonl reference', () => {
    expect(checkBrandExposure('See events.jsonl for details')).toBeInstanceOf(RegExp);
  });
});

describe('@qa/contracts — LessonEntrySchema', () => {
  const ISO = '2026-05-25T00:00:00.000Z';

  const validLesson = {
    id: 'L-TD-001',
    polarity: 'negative',
    trigger: 'spv-rejection',
    mistake: 'Skipped asserting response headers in API tests causing missed regressions',
    rootCause: 'Test focused on status code only, missing header validation entirely',
    correctiveRule: 'Always assert Content-Type and Cache-Control headers in API tests',
    evidence: [],
    firstSeen: ISO,
    lastSeen: ISO,
    hitCount: 1,
  };

  it('parses a valid lesson entry', () => {
    expect(() => LessonEntrySchema.parse(validLesson)).not.toThrow();
  });

  it('rejects correctiveRule that does not start with uppercase', () => {
    expect(() =>
      LessonEntrySchema.parse({ ...validLesson, correctiveRule: 'always assert headers in tests' })
    ).toThrow();
  });

  it('rejects hitCount of zero', () => {
    expect(() =>
      LessonEntrySchema.parse({ ...validLesson, hitCount: 0 })
    ).toThrow();
  });

  it('rejects mistake shorter than 20 chars', () => {
    expect(() =>
      LessonEntrySchema.parse({ ...validLesson, mistake: 'Too short' })
    ).toThrow();
  });
});
