import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export interface RoleCredentials {
  role: string;
  email: string;
  password?: string;
  jwtOverride?: string; // pre-forged JWT for Supabase
}

export interface AuthFixtureConfig {
  roles: string[];           // e.g. ["admin", "manager", "user", "anon"]
  loginUrl: string;          // e.g. "/login"
  logoutUrl?: string;        // e.g. "/api/logout" — if not set, UI click fallback
  stateDir: string;          // absolute path e.g. "tests/state/"
  credentialsDir: string;    // absolute path to aegis/test-data/credentials/
  baseUrl: string;
}

// ─── Fixture generators ───────────────────────────────────────────────────────

// Generate the auth.fixture.ts file content (string) for a target project.
// The generated file imports from @playwright/test and exports role-specific fixtures.
export function generateAuthFixtureContent(config: AuthFixtureConfig): string {
  const { roles, stateDir } = config;
  const nonAnonRoles = roles.filter((r) => r !== "anon");
  const hasAnon = roles.includes("anon");

  const fixtureTypeLines = roles.map((r) => `  ${r}Page: Page`).join(";\n");

  const fixtureImpls = nonAnonRoles
    .map(
      (role) => `  ${role}Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: resolve(__dirname, ${JSON.stringify(join(stateDir, `${role}.json`))}),
    });
    const page = await ctx.newPage();
    await use(page);
    await page.context().clearCookies();
    await page.close();
    await ctx.close();
  },`,
    )
    .join("\n\n");

  const anonImpl = hasAnon
    ? `\n\n  anonPage: async ({ browser }, use) => {
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await use(page);
    await page.close();
    await ctx.close();
  },`
    : "";

  return `// Auto-generated by @qa/auth-fixtures — do not hand-edit
import { test as base, type Page } from '@playwright/test';
import { resolve } from 'node:path';

type Fixtures = {
${fixtureTypeLines};
};

export const test = base.extend<Fixtures>({
${fixtureImpls}${anonImpl}
});

export { expect } from '@playwright/test';
`;
}

// Generate global-setup.ts content for Playwright.
export function generateGlobalSetupContent(config: AuthFixtureConfig): string {
  const { roles, loginUrl, stateDir, baseUrl } = config;
  const nonAnonRoles = roles.filter((r) => r !== "anon");

  const loginBlocks = nonAnonRoles
    .map(
      (role) => `
  // ── ${role} ──
  {
    const ROLE = ${JSON.stringify(role)};
    const email = process.env[${JSON.stringify(`${role.toUpperCase()}_EMAIL`)}];
    const password = process.env[${JSON.stringify(`${role.toUpperCase()}_PASSWORD`)}];
    if (!email || !password) {
      console.error(\`[global-setup] Missing credentials for role "${role}". Set ${role.toUpperCase()}_EMAIL and ${role.toUpperCase()}_PASSWORD.\`);
      process.exit(1);
    }
    const context = await browser.newContext();
    const page = await context.newPage();
    try {
      await page.goto(${JSON.stringify(baseUrl + loginUrl)});
      await page.getByLabel(/email/i).fill(email);
      await page.getByLabel(/password/i).fill(password);
      await page.getByRole('button', { name: /sign in|log in|login/i }).click();
      await page.waitForURL((url) => !url.pathname.includes(${JSON.stringify(loginUrl)}), { timeout: 10_000 });
      await context.storageState({ path: resolve(${JSON.stringify(stateDir)}, \`\${ROLE}.json\`) });
    } catch (err) {
      console.error(\`[global-setup] Login failed for role "${role}":\`, err);
      await page.close();
      await context.close();
      process.exit(1);
    }
    await page.close();
    await context.close();
  }`,
    )
    .join("\n");

  return `// Auto-generated by @qa/auth-fixtures — do not hand-edit
import { chromium } from '@playwright/test';
import { resolve } from 'node:path';

export default async function globalSetup(): Promise<void> {
  const browser = await chromium.launch();
${loginBlocks}

  await browser.close();
}
`;
}

// Generate global-teardown.ts content for Playwright.
export function generateGlobalTeardownContent(config: AuthFixtureConfig): string {
  const { stateDir } = config;

  return `// Auto-generated by @qa/auth-fixtures — do not hand-edit
import { readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

export default async function globalTeardown(): Promise<void> {
  const stateDir = ${JSON.stringify(stateDir)};
  try {
    const files = readdirSync(stateDir);
    for (const file of files) {
      if (file.endsWith('.json')) {
        unlinkSync(join(stateDir, file));
      }
    }
  } catch {
    // stateDir may not exist if setup was skipped
  }
}
`;
}

// ─── Credential helpers ───────────────────────────────────────────────────────

// Load credentials for a role from {credentialsDir}/{role}.env.local
// Returns null if file doesn't exist.
export function loadRoleCredentials(
  credentialsDir: string,
  role: string,
): RoleCredentials | null {
  const filePath = join(credentialsDir, `${role}.env.local`);
  if (!existsSync(filePath)) {
    return null;
  }

  const contents = readFileSync(filePath, "utf8");
  const lines = contents.split("\n");

  const entries: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");
    if (key) {
      entries[key] = value;
    }
  }

  const email = entries["EMAIL"] ?? entries[`${role.toUpperCase()}_EMAIL`] ?? "";
  const password =
    entries["PASSWORD"] ?? entries[`${role.toUpperCase()}_PASSWORD`] ?? undefined;
  const jwtOverride =
    entries["JWT_OVERRIDE"] ??
    entries[`${role.toUpperCase()}_JWT_OVERRIDE`] ??
    undefined;

  return {
    role,
    email,
    ...(password !== undefined ? { password } : {}),
    ...(jwtOverride !== undefined ? { jwtOverride } : {}),
  };
}

// Validate all required credential files exist.
export function validateCredentialsExist(
  credentialsDir: string,
  roles: string[],
): { valid: boolean; missing: string[] } {
  const missing: string[] = [];

  for (const role of roles) {
    const filePath = join(credentialsDir, `${role}.env.local`);
    if (!existsSync(filePath)) {
      missing.push(role);
    }
  }

  return {
    valid: missing.length === 0,
    missing,
  };
}
